name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          mkdir ../build
          go build -o ../build/app cmd/main.go
          cp -TR . ../build
          tar -cvf deploy.tar ../build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy.tar"
          target: "${{secrets.TARGET_DIR}}"

      - name: Run app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{secrets.TARGET_DIR}}
            shopt -s extglob
            rm -r !(.env)
            tar -xvf deploy.tar --strip-components=1
            nohup ./app &
